name: hash
description: A set of cryptographic hashing functions implemented in pure Dart
version: 1.0.3
homepage: https://github.com/litaoh/hash

environment:
  sdk: '>=2.12.0 <3.0.0'


dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8