name: hash
description: A set of cryptographic hashing functions implemented in pure Dart
version: 1.0.2
homepage: https://github.com/litaoh/hash

environment:
  sdk: '>=2.0.0 <3.0.0'


dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
